<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions targetNamespace="http://soap.wscursus.jtechnologies.ordina.nl/" name="HelloService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://soap.wscursus.jtechnologies.ordina.nl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://soap.wscursus.jtechnologies.ordina.nl/" schemaLocation="HelloService.xsd"/>
        </xsd:schema>
        <!--<xsd:schema version="1.0" targetNamespace="http://soap.wscursus.jtechnologies.ordina.nl/"-->
                    <!--xmlns:tns="http://soap.wscursus.jtechnologies.ordina.nl/"-->
                    <!--xmlns:xsd="http://www.w3.org/2001/XMLSchema">-->
            <!--<xsd:element name="sayHello" type="xsd:string"/>-->
            <!--<xsd:element name="sayHelloResponse" type="xsd:string"/>-->
        <!--</xsd:schema>-->
    </types>
    <message name="sayHelloRequest">
        <part name="argument" element="tns:sayHello"/>
    </message>
    <message name="sayHelloResponse">
        <part name="return" element="tns:sayHelloResponse"/>
    </message>
    <portType name="Hello">
        <operation name="sayHello">
            <input message="tns:sayHelloRequest"/>
            <output message="tns:sayHelloResponse"/>
        </operation>
    </portType>
    <binding name="HelloPortBinding" type="tns:Hello">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="sayHello">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="HelloService">
        <port name="HelloPort" binding="tns:HelloPortBinding">
            <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
        </port>
    </service>
</definitions>

