
package nl.ordina.jtechnologies.wscursus.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://soap.wscursus.jtechnologies.ordina.nl/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param argument
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sayHelloResponse", targetNamespace = "http://soap.wscursus.jtechnologies.ordina.nl/", partName = "return")
    public String sayHello(
        @WebParam(name = "sayHello", targetNamespace = "http://soap.wscursus.jtechnologies.ordina.nl/", partName = "argument")
        String argument);

}
